### ISSUE TITLE
[DO NOT CLOSE] Images for wiki page

### ISSUE THREAD

**Issue by koenderks** [jasp-stats/jaspProcessControl#10]
This issue serves as a place to post any images to are required for the wiki page. 

Current module layout:
![image](https://user-images.githubusercontent.com/25059399/101484986-c92de480-395a-11eb-904c-0f3cbe72f7ae.png)

Current state of process capability analysis:
![image](https://user-images.githubusercontent.com/25059399/97413532-30d82500-1903-11eb-87fa-bee3466c6a52.png)

Current state of process control analysis:
![image](https://user-images.githubusercontent.com/25059399/97413588-40f00480-1903-11eb-9e62-9a6af881a0bd.png)

Current state of measurement system analysis:
![image](https://user-images.githubusercontent.com/25059399/97413705-64b34a80-1903-11eb-8d43-d6c5c98755d9.png)

Current state of design of experiments analysis:
![image](https://user-images.githubusercontent.com/25059399/101484902-a0a5ea80-395a-11eb-8f4d-547a6e85da53.png)

**Comment by tomishay** [comment]
![1](https://user-images.githubusercontent.com/71082046/98385010-c9cb1680-204e-11eb-942e-591e69641b0f.JPG)
