### ISSUE TITLE
Testing: MSA

### ISSUE THREAD

**Issue by tomishay** [jasp-stats/jaspProcessControl#128]
Please test the module and report the errors.

**Comment by knrds** [comment]
Analysis: Type 1 Instrument Capability
Issue: unchecking 'bias and instrument capability table' doesn't remove said table
Steps: enter 'Measurements', uncheck 'bias and instrument capability table'

**Comment by knrds** [comment]
Analysis: Type 2 and 3 Gauge r&R
Issue: 'Report' remains in output after unchecking checkbox
Steps: check 'Type 3 study', enter 'Measurements' and 'Parts', fill in 'ANOVA Method Report', check 'Show Report', uncheck 'Show Report'

**Comment by knrds** [comment]
Analysis: Type 2 and 3 Gauge r&R
Issue: traffic light plot y-axis misspelled, "Precent" instead of "Percent"
