### ISSUE TITLE
Testing: Control Charts 

### ISSUE THREAD

**Issue by tomishay** [jasp-stats/jaspProcessControl#129]

**Comment by koenderks** [comment]
Found issues so far:

*Variables charts for subgroups*
- [ ] Help files!
- [ ] `contGamma` from `debug.csv` gives weird results in the R chart. Table shows 1 outlier but there are multiple red dots in the graph.
![image](https://user-images.githubusercontent.com/25059399/143551798-737bda4b-58f1-4287-8823-b6bacd38269b.png)
- [ ] Maybe the default value for `standard deviation` should be 3 (six sigma)?

*Variables charts for individuals*
- [ ] Help files!
- [ ] Setting `number of lags` to 0 crashes analysis.
- [ ] `confidence interval` should not be able to be 0.
- [ ] Isn't it weird to have an autocorrelation of 1 for the first lag? Wouldn't this mean every data point is the same?
![image](https://user-images.githubusercontent.com/25059399/143552808-874a37d5-275b-46f8-bc6f-6cc8cccc49c0.png)


*Control charts for attributes* (@tomishay Do you have a data set I can test this analysis with?)
- [ ] Help files!
- [ ] Entering just `facFifty` in `Sample` gives the error message `Number of observations is  < 2 in`. In what? 

*Time weighted charts*
- [ ] Help files!
- [ ] Cumulative sum chart title of plot should be capitalized
- [ ] Changing `number of standard deviations` or `shift size` does not refresh the cumulative sum chart (missing dependency)
- [ ] Changing any option does not refresh the `Exponentially weighted moving average chart`
- [ ] g chart crashed analysis using `contNormal` and `contGamma` from `debug.csv` --> `Object 'y' not found`
- [ ] Using just `contNormal` for g chart gives: `Discrete value supplied to continuous scale`
- [ ] Same issues for t chart.
- [ ] Green lines in plots should be cut off at the end of the plot?
