### ISSUE TITLE
Bugs and additions to the new release 

### ISSUE THREAD

**Issue by tomishay** [jasp-stats/jaspProcessControl#162]
**Help files**
- [ ] Edit/add citations. [40b4bfa](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/40b4bfa63511f30ace34a9ae6d00fa5d87264d59). 
- [ ] Explnation for nelson tests of control charts. [40b4bfa](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/40b4bfa63511f30ace34a9ae6d00fa5d87264d59). 

**Common quality control**
- [ ] Don't mark points outside of control limits when more than half violate the limits. [0b05631](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/0b056317e9f8a276c881c98639e1219ada0a1aee). 
- [ ] Replcae I by II for vectorized condtionals. [0b05631](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/0b056317e9f8a276c881c98639e1219ada0a1aee). 

**MSA**
 _Gauge r&R_ 
- [ ] Set fixed effects model as default.  [0b05631](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/0b056317e9f8a276c881c98639e1219ada0a1aee). 
- [ ] Decrease the number of x-axis ticks for the probability plot. [0b05631](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/0b056317e9f8a276c881c98639e1219ada0a1aee). 
- [ ] Remove the rounding of the summary table in the report (which generated an error). [0b05631](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/0b056317e9f8a276c881c98639e1219ada0a1aee).
- [ ] Add the values of the horizontal line in the traffic light plot. [9594b8e](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/9594b8e6740faaa456366d17e8edee3cc09a32c1).
- [ ] Repalce NA by zero for part-to-part variance. [5faeb2f](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5faeb2f2a6d887e9f85c5e0f4bc8edd32ee9e93a). 
- [ ] When the report is ticked, remove all other plots [08d183d](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/08d183d050f45f3bc80c593b443306c1f5f8ec6d). 

_Process capability studies_
- [ ] Check if values are non-zero and positive for non-nomral capability study. [5faeb2f](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5faeb2f2a6d887e9f85c5e0f4bc8edd32ee9e93a). 
- [ ] Use the same symbols for the parameters of the Weibull/Lognormal distributions. [5faeb2f](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5faeb2f2a6d887e9f85c5e0f4bc8edd32ee9e93a). 
- [ ] Correction for zero values in non-normal capability: adds a warning message and replaces zero by the half of the smallest data point. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94).  
- [ ] Adjust the probability plot function forTwo level factorial analysis. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Display the control charts above one another in the report. [1d63d90](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/1d63d90c4492cc678cbb7a746b6f838cb0ee00b3). 
- [ ] Change the order of plots display in the report. [1d63d90](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/1d63d90c4492cc678cbb7a746b6f838cb0ee00b3). 
- [ ] When the report is ticked, remove all other plots [08d183d](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/08d183d050f45f3bc80c593b443306c1f5f8ec6d). 

 _Gauge r&R non-replicable_ 
- [ ] Check for NA before removing it. [9594b8e](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/9594b8e6740faaa456366d17e8edee3cc09a32c1).
- [ ] When the report is ticked, remove all other plots [08d183d](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/08d183d050f45f3bc80c593b443306c1f5f8ec6d). 

_Attribtue_
- [ ] Check for missing values before removing them. [9594b8e](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/9594b8e6740faaa456366d17e8edee3cc09a32c1).

**Control Charts**
- [ ] When the report is ticked, remove all other plots [08d183d](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/08d183d050f45f3bc80c593b443306c1f5f8ec6d). 

_Attributes_
- [ ] Add time stamp. [0b05631](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/0b056317e9f8a276c881c98639e1219ada0a1aee). 
- [ ] Improve the specification of the dependencies. [9594b8e](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/9594b8e6740faaa456366d17e8edee3cc09a32c1).

**DOE**
_Screeining_
- [ ] Change default values for the number of factors. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 

_Two level factorial_
- [ ] Use the correct values for the Pareto plot. [72d4095](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/72d40952e40ec9c83ccfb35155be6afdd0a9bb3f).
- [ ] Code uncoded input into -1 and 1. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Remove normal probability plot of standardized effects. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Correction for the normal probability plot of residuals. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Make a container for the results and a container for the design. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Use frquncy and not percentage for the residauls histogram. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Round error terms in the Anova table. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Space the terms and coefs in the regression formula. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Add "VIf" values in the coefs table. [5b1be16](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/5b1be16a2e4667156c0ef94972c0af94a91d5b94). 
- [ ] Correct resolution of design. [1d63d90](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/1d63d90c4492cc678cbb7a746b6f838cb0ee00b3)
- [ ] Show uncoded lower levels when the lower level is equal to 1. [1d63d90](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/1d63d90c4492cc678cbb7a746b6f838cb0ee00b3)
- [ ] Move the type of distribution for the probability plot to advance options. [08d183d](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/08d183d050f45f3bc80c593b443306c1f5f8ec6d). 

_Response surface methodology_
- [ ] Set seed for the random design. [6b2cdb2](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/6b2cdb2ad0fa5e7a086d6552dc29fbc5e8afd51c).
- [ ] Comment the formula and names options out. [6b2cdb2](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/6b2cdb2ad0fa5e7a086d6552dc29fbc5e8afd51c). 
- [ ] Always randomize the created design. [6b2cdb2](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/6b2cdb2ad0fa5e7a086d6552dc29fbc5e8afd51c). 
- [ ] Change the GUI and default settings. [6b2cdb2](https://github.com/jasp-stats/jaspProcessControl/pull/161/commits/6b2cdb2ad0fa5e7a086d6552dc29fbc5e8afd51c).

**Comment by vandenman** [comment]
Closing this as #161 is merged
