### ISSUE TITLE
Design MSA user interface

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jaspProcessControl#2]
Please submit a PR with changes to inst/qml/measurementSystemAnalysis.qml

**Comment by koenderks** [comment]
Some examples from minitab:
![image](https://user-images.githubusercontent.com/25059399/96988332-7b812800-1524-11eb-988f-d9a02939718f.png)
![image](https://user-images.githubusercontent.com/25059399/96988277-699f8500-1524-11eb-8591-c2a6686ba0b7.png)
![image](https://user-images.githubusercontent.com/25059399/96988295-70c69300-1524-11eb-9b7c-3c713e9f865e.png)
