### ISSUE TITLE
 Design design of experiments

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jaspProcessControl#5]
Please submit a PR with changes to inst/qml/designOfExperiments.qml

**Comment by koenderks** [comment]
Some examples in minitab:
![image](https://user-images.githubusercontent.com/25059399/96987570-7e2f4d80-1523-11eb-8dbf-7fadf71a0c28.png)
![image](https://user-images.githubusercontent.com/25059399/96987624-8edfc380-1523-11eb-8405-a11d6b5bf64c.png)
![image](https://user-images.githubusercontent.com/25059399/96987761-b9318100-1523-11eb-95f5-0d6d11b743c5.png)
![image](https://user-images.githubusercontent.com/25059399/96987804-c3ec1600-1523-11eb-830f-41f0f8a5699b.png)
![image](https://user-images.githubusercontent.com/25059399/96988169-4379e500-1524-11eb-9e9a-fbf2c377c96d.png)
