### ISSUE TITLE
Feedback after meeting 15-02-2021

### ISSUE THREAD

**Issue by koenderks** [jasp-stats/jaspProcessControl#52]
**All analyses**
- [x] Add option to change dots to lines for when there are many data points.
- [x] Be consistent with JASP using capital letters in option names.
- [ ] Charts' x-axis is rescaled after editing a plot (for @vandenman).
- [ ] Charts add the option to specify separate (per operator for example) and joint (all operators together).
- [x] Check x-axis ticks when using discrete variables (usually JASP does not show the line but only the ticks).

**Type-1 Gauge**
- [ ] Adjust placing of labels in the run chart so they do not overlap and make them bigger.
![image](https://user-images.githubusercontent.com/25059399/107961509-4eaac200-6fa6-11eb-86bf-1e66f7922b0a.png)
- [x] Add options for specifying the breaks to the histogram.
- [x] Change table names and overtitle of `CI` for bias to be consistent (so `Lower` and `Upper` and add `for bias` to the overtitle).

**Gauge r&R**
- [ ] Check and verify how F-value is computed in the ANOVA table.
- [x] Change title `Graphs` to Plots`.
- [x] Change `Value` of the standard deviation to `SD value` or something.
- [x] Remove the x-axis line for the Variation Components graph (standard JASP uses only ticks for discrete groups).
- [ ] Fix the range y-axis of the Variation Components Graph.
- [ ] Under graphs, implement an option to set the x-axes for all plots at the same time.
- [ ] Make a matrix plot (mirror correlation analysis scatter plots) for the scatter plot operators graph.
- [ ] Table for descriptive information from the box plots.
- [ ] Parts by operator interaction graph should have dots and lines that are bigger and more consistent with jaspGraphs.

**Attribute Agreement Analysis**
- [ ] Add confidence intervals to Fleiss' Kappa, Cohen's Kappa, and Kendall's Tau to the tables.

**Comment by JTPetter** [comment]
@koenderks thanks for the nice overview!
