### ISSUE TITLE
Bugs in Attribute Charts

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jaspProcessControl#63]
[AttributeCharts.zip](https://github.com/jasp-stats/jaspProcessControl/files/6090841/AttributeCharts.zip)

One minor bug, see attached.

**Comment by tomishay** [comment]
Thanks! 
I am trying to check for equal samples sizes in the Sample field, but I cannt get it to work. Any ideas why?

`  .hasErrors(dataset,
             all.target = options$total,
             custom = function() {if (length(unique(options$total)) > 1) return("Samples must be equal in size")}
             , exitAnalysisIfErrors = TRUE)`

**Comment by vandenman** [comment]
you're looking at the options, not at the data itself. Maybe 
```r
.hasErrors(
  dataset, 
  all.target = options$total, 
  custom = function() {
    if (length(unique(dataset[[options$total]])) > 1) 
      return("Samples must be equal in size")
  }, 
  exitAnalysisIfErrors = TRUE
)
```
?
